In [6]:
import pandas as pd
df = pd.read_csv('Atlanta.csv')
print(df.shape)

(41126, 26)


In [7]:
df.isnull().sum()

Severity                    0
Description                 0
Weather_Timestamp          91
Temperature(F)            166
Humidity(%)               172
Pressure(in)              100
Visibility(mi)            156
Wind_Speed(mph)          5552
Weather_Condition         138
Amenity                     0
Bump                        0
Crossing                    0
Give_Way                    0
Junction                    0
No_Exit                     0
Railway                     0
Roundabout                  0
Station                     0
Stop                        0
Traffic_Calming             0
Traffic_Signal              0
Turning_Loop                0
Sunrise_Sunset              0
Civil_Twilight              0
Nautical_Twilight           0
Astronomical_Twilight       0
dtype: int64

In [9]:
column_means = df.mean()
df = df.fillna(column_means)
print(df.isnull().sum())

Severity                   0
Description                0
Weather_Timestamp         91
Temperature(F)             0
Humidity(%)                0
Pressure(in)               0
Visibility(mi)             0
Wind_Speed(mph)            0
Weather_Condition        138
Amenity                    0
Bump                       0
Crossing                   0
Give_Way                   0
Junction                   0
No_Exit                    0
Railway                    0
Roundabout                 0
Station                    0
Stop                       0
Traffic_Calming            0
Traffic_Signal             0
Turning_Loop               0
Sunrise_Sunset             0
Civil_Twilight             0
Nautical_Twilight          0
Astronomical_Twilight      0
dtype: int64


In [10]:
df = df.dropna()
print(df.isnull().sum())
print(df.shape)

Severity                 0
Description              0
Weather_Timestamp        0
Temperature(F)           0
Humidity(%)              0
Pressure(in)             0
Visibility(mi)           0
Wind_Speed(mph)          0
Weather_Condition        0
Amenity                  0
Bump                     0
Crossing                 0
Give_Way                 0
Junction                 0
No_Exit                  0
Railway                  0
Roundabout               0
Station                  0
Stop                     0
Traffic_Calming          0
Traffic_Signal           0
Turning_Loop             0
Sunrise_Sunset           0
Civil_Twilight           0
Nautical_Twilight        0
Astronomical_Twilight    0
dtype: int64
(40988, 26)


In [12]:
df.to_csv("Atlanta_main.csv")

In [13]:
col_list = ["Severity", "Description"]
df = pd.read_csv("Atlanta_main.csv", usecols=col_list)
df

Severity                                        Description
0             0                     At Habersham Rd NE - Accident.
1             0            Accident on Hank Aaron Dr at Ormond St.
2             0       At GA-10/Freedom Pky/Exit 248 NB - Accident.
3             0              Accident on Peachtree St near 8th St.
4             1  Shoulder blocked on exit ramp due to accident ...
...         ...                                                ...
40983         1  Accident on I-75 Southbound around Exits 248B ...
40984         1  Two lanes blocked due to accident on I-285 Wes...
40985         1  Entry ramp to I-285 anticlockwise from I-85 So...
40986         1  Right hand shoulder blocked and right lane blo...
40987         1  Entry ramp to I-85 Northbound at Exits 250 251...

[40988 rows x 2 columns]

In [14]:
df.to_csv("Atlanta_Desc_main.csv")

In [15]:
col_list = ["Severity", "Amenity", "Bump", "Crossing", "Give_Way", "Junction", "No_Exit", "Railway", "Roundabout","Station","Stop","Traffic_Calming","Traffic_Signal"]
df = pd.read_csv("Atlanta_main.csv", usecols=col_list)
df

Severity  Amenity   Bump  Crossing  Give_Way  Junction  No_Exit  \
0             0    False  False     False     False     False    False   
1             0    False  False      True     False     False    False   
2             0    False  False     False     False     False    False   
3             0    False  False     False     False     False    False   
4             1    False  False     False     False     False    False   
...         ...      ...    ...       ...       ...       ...      ...   
40983         1    False  False     False     False     False    False   
40984         1    False  False     False     False     False    False   
40985         1    False  False     False     False     False    False   
40986         1    False  False     False     False      True    False   
40987         1    False  False     False     False      True    False   

       Railway  Roundabout  Station   Stop  Traffic_Calming  Traffic_Signal  
0        False       False    False  False            False           False  
1        False       False    False  False            False           False  
2        False       False    False  False            False           False  
3        False       False    False  False            False            True  
4        False       False    False  False            False           False  
...        ...         ...      ...    ...              ...             ...  
40983    False       False    False  False            False           False  
40984    False       False    False  False            False           False  
40985    False       False    False  False            False           False  
40986    False       False    False  False            False           False  
40987    False       False    False  False            False           False  

[40988 rows x 13 columns]

In [16]:
df.to_csv("Atlanta_POI_main.csv")

In [20]:
col_list = ["Weather_Timestamp", "Temperature(F)", "Humidity(%)", "Pressure(in)", "Visibility(mi)", "Wind_Speed(mph)", "Weather_Condition", "Sunrise_Sunset", "Civil_Twilight","Nautical_Twilight","Astronomical_Twilight","Severity"]
df = pd.read_csv("Atlanta_main.csv", usecols=col_list)
df

Severity Weather_Timestamp  Temperature(F)  Humidity(%)  Pressure(in)  \
0             0     6/17/16 15:53            73.9         71.0         29.78   
1             0      6/21/16 8:52            75.0         60.0         30.16   
2             0      6/21/16 9:52            79.0         56.0         30.16   
3             0      6/21/16 9:53            80.1         56.0         30.16   
4             1     6/21/16 10:52            82.9         51.0         30.16   
...         ...               ...             ...          ...           ...   
40983         1     6/30/20 18:53            74.0         87.0         29.08   
40984         1     6/30/20 18:53            75.0         87.0         28.91   
40985         1     6/30/20 18:53            75.0         87.0         28.91   
40986         1     6/30/20 20:53            73.0         87.0         29.07   
40987         1     6/30/20 21:53            74.0         82.0         29.07   

       Visibility(mi)  Wind_Speed(mph) Weather_Condition Sunrise_Sunset  \
0                10.0              3.5             Clear            Day   
1                10.0             10.4  Scattered Clouds            Day   
2                10.0              8.1     Partly Cloudy            Day   
3                10.0              8.1             Clear            Day   
4                10.0             11.5     Partly Cloudy            Day   
...               ...              ...               ...            ...   
40983            10.0              7.0              Fair            Day   
40984            10.0              3.0     Mostly Cloudy            Day   
40985            10.0              3.0     Mostly Cloudy            Day   
40986            10.0              0.0              Fair          Night   
40987            10.0              3.0              Fair          Night   

      Civil_Twilight Nautical_Twilight Astronomical_Twilight  
0                Day               Day                   Day  
1                Day               Day                   Day  
2                Day               Day                   Day  
3                Day               Day                   Day  
4                Day               Day                   Day  
...              ...               ...                   ...  
40983            Day               Day                   Day  
40984            Day               Day                   Day  
40985            Day               Day                   Day  
40986            Day               Day                   Day  
40987          Night             Night                   Day  

[40988 rows x 12 columns]

In [21]:
df.to_csv("Atlanta_Weather_main.csv")

In [22]:
import os
import sys
import psutil

import pandas as pd
import numpy as np
import tensorflow as tf
import keras
import random
np.random.seed(0)
from keras.models import Sequential,Model
from keras.layers import Dense,LSTM,Activation,Dropout,BatchNormalization,Input,Embedding,Reshape,Concatenate, GRU
from keras.layers import Flatten,Conv2D,MaxPooling2D,Bidirectional,concatenate

from keras.utils import to_categorical
from keras.callbacks import EarlyStopping
from keras import regularizers
from keras import optimizers
import keras_metrics as km

import matplotlib
import matplotlib.pyplot as plt
import math
from multiprocessing import cpu_count,Pool 
import multiprocessing


from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

from keras.utils import np_utils
from sklearn.metrics import recall_score,precision_score,f1_score,accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

from sklearn.metrics import make_scorer
from keras.wrappers.scikit_learn import KerasClassifier


from sklearn.metrics import roc_curve, auc

from scipy import interp
import matplotlib.pyplot as plt
from itertools import cycle

from keras_self_attention import SeqSelfAttention

from utils import *
from base import *

from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics

In [23]:
import tensorflow as tf
tf.__version__

'2.2.0'

In [24]:
verbose = 2
dropout=0.2
VAL_SPLIT = 0.2
patience = 15
lr=0.01
weight_decay = 0.0000
lr_decay=1e-6
ADD_ON_LAYERS = True
ACT_PRIOR = 'sigmoid'
ACT_POSTERIOR = 'relu'
LSTM_UNIT = 128
LSTM_UNIT1 = 64
LSTM_UNIT2 = 32 
GEOHASH_UNIT = 128
EMBEDDING_UNIT = 128
Embedding_outdim = 128
NLP_UNIT = 128
SEQ_UNIT = 256
DENSE_CONCAT = 256
CONV_UNIT = 32
weights = np.array([1,1])

In [28]:
import pandas as pd
df = pd.read_csv('Atlanta_Weather_main.csv')
print(df.shape)

(40988, 12)


In [29]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder
timestep = 20
file = np.array(df)
file_X = file[:, 1:-1]
file_y = file[:, -1]

del file
print(file_X[0])
print(file_X.shape)
def prepare_inputs(X_train, X_test):
    ohe = OneHotEncoder(sparse = False)
    #ohe.fit(X_train[:,5:])
    X_train_enc = ohe.fit_transform(X_train[:,5:])
    #X_train_enc = np.asarray(X_train_enc)
    #X = []
    #for i in range(len(X_train_enc)):
    #    X.append(X_train_enc[i,:])
    #X= np.array(X)
    #print(X.shape)
#     print(X_train_enc.dtype)
#     X_train_enc = np.array(X_train_enc)
#     print(X_train_enc.shape)
#     X_train_enc = np.pad(X_train_enc, (5,0),'constant', constant_values=0)
    #X_test_enc = ohe.transform(X_test)
    X_train_enc = np.array(X_train_enc)
    X_train_enc = np.c_[X_train[:,:5], X_train_enc]
    print(X_train_enc[0])
    print(X_train_enc.shape)
    return X_train_enc

file_X = prepare_inputs(file_X, file_y)

[73.9 71.0 29.78 10.0 3.5 'Clear' 'Day' 'Day' 'Day' 'Day']
(40988, 10)
[73.9 71.0 29.78 10.0 3.5 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
 1.0 0.0 1.0 0.0 1.0 0.0]
(40988, 59)


In [30]:
print(file_X.shape)
print(file_y.shape)

(40988, 59)
(40988,)


In [31]:
X = []
y = []
file_X = np.array(file_X, dtype = np.float64)
for i in range(0, len(file_X)-timestep):
    X.append(file_X[i:i+timestep])
    y.append(file_y[i+timestep])
X= np.array(X)
y= np.array(y)
print(X.dtype)

float64


In [32]:
print(X.shape)
print(y.shape)

(40968, 20, 59)
(40968,)


In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [34]:
print(X_test.shape)
print(y_test.shape)

(13520, 20, 59)
(13520,)


In [35]:
docs = pd.read_csv('Atlanta_Desc_main.csv')
doc=docs.to_numpy()

In [36]:
docs=doc[:,1]

In [37]:
docs.shape

(40988,)

In [38]:
labels = doc[:,0]

In [39]:
labels.shape

(40988,)

In [40]:
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
top_words = 500
max_review_length = 50
encoded_docs = [one_hot(d, top_words) for d in docs]
print(encoded_docs)

[[445, 487, 196, 497, 109], [109, 478, 345, 314, 237, 445, 308, 243], [445, 189, 235, 2, 284, 84, 255, 65, 109], [109, 478, 134, 243, 190, 145, 243], [47, 135, 478, 84, 472, 161, 329, 109, 478, 252, 92, 388, 445, 252, 122, 252, 149, 65], [132, 385, 135, 161, 329, 109, 478, 252, 92, 388, 51, 84, 298, 189, 310, 60, 348, 28], [431, 385, 135, 161, 329, 109, 478, 252, 92, 388, 341, 252, 217], [314, 132, 385, 135, 161, 329, 109, 478, 252, 149, 252, 122, 172, 445, 134, 243], [109, 478, 189, 367, 134, 196, 445, 189, 5, 130, 196], [109, 478, 252, 217, 141, 445, 252, 92], [109, 478, 252, 149, 252, 122, 172, 445, 84, 192, 290, 124], [104, 106, 135, 161, 329, 109, 478, 252, 92, 388, 445, 84, 298, 189, 310, 60, 348, 28], [109, 478, 5, 461, 134, 196, 445, 189, 498, 319, 237], [109, 478, 252, 217, 172, 445, 84, 378, 189, 375, 487, 381, 241, 482, 237], [109, 478, 252, 149, 252, 122, 141, 445, 84, 131, 21, 243], [109, 478, 5, 426, 176, 124, 172, 445, 472, 286, 21, 237], [337, 243, 237, 84, 312, 26, 381

In [41]:
from keras.preprocessing import sequence
X_train2, X_test2, y_train2, y_test2 = train_test_split(encoded_docs, labels, test_size=0.33, random_state=42)
X_train2 = sequence.pad_sequences(X_train2, maxlen=max_review_length)
X_test2 = sequence.pad_sequences(X_test2, maxlen=max_review_length)

In [42]:
print(y_train2)
print(y_train2.shape)

[0 1 1 ... 1 1 0]
(27461,)


In [43]:
X_train2= np.array(X_train2)
X_train2

array([[  0,   0,   0, ..., 445, 258, 243],
       [  0,   0,   0, ..., 149, 252, 122],
       [  0,   0,   0, ..., 389, 412, 196],
       ...,
       [  0,   0,   0, ..., 431, 212, 196],
       [  0,   0,   0, ..., 161, 329, 109],
       [  0,   0,   0, ...,  84, 313, 109]], dtype=int32)

In [44]:
y_train2= np.array(y_train2)
y_train2.shape

(27461,)

In [45]:
X_train2.shape

(27461, 50)

In [46]:
# example of learned embedding encoding for a neural network
import numpy as np
from numpy import unique
from pandas import read_csv
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.models import Model
from keras.layers import Input
from keras.layers import Dense
from keras.layers import Embedding
from keras.layers.merge import concatenate
from keras.utils import plot_model
from keras.layers import Dropout
from sklearn.preprocessing import OneHotEncoder

In [47]:
import pandas as pd
df = pd.read_csv('Atlanta_POI_main.csv')

In [48]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder
timestep = 20
file = np.array(df)
file_X = file[:, 1:]
file_y = file[:, 0:1]

print(file_X.shape)
print(file_y.shape)
def prepare_inputs(X_train, X_test):
    ohe = OneHotEncoder(sparse = False)
    #ohe.fit(X_train[:,5:])
    X_train_enc = ohe.fit_transform(X_train[:,:])
    #X_train_enc = np.asarray(X_train_enc)
    #X = []
    #for i in range(len(X_train_enc)):
    #    X.append(X_train_enc[i,:])
    #X= np.array(X)
    #print(X.shape)
#     print(X_train_enc.dtype)
#     X_train_enc = np.array(X_train_enc)
#     print(X_train_enc.shape)
#     X_train_enc = np.pad(X_train_enc, (5,0),'constant', constant_values=0)
    #X_test_enc = ohe.transform(X_test)
    X_train_enc = np.array(X_train_enc)
#     X_train_enc = np.c_[X_train[:,:5], X_train_enc]
    print(X_train_enc[0])
    print(X_train_enc.shape)
    return X_train_enc

file_X = prepare_inputs(file_X, file_y)

(40988, 12)
(40988, 1)
[1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0.]
(40988, 22)


In [49]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(file_X, file_y, test_size=0.33, random_state=42)

In [50]:
print(X_train.shape)
print(y_train.shape)

(27461, 22)
(27461, 1)


In [53]:
X_train
y_train

array([[0],
       [1],
       [1],
       ...,
       [1],
       [1],
       [0]], dtype=object)

In [54]:
DENSE_CONCAT = 512
top_words = 500
max_review_length = 50
embedding_vecor_length = 32
weight_decay = 0.0000
dropout=0.2
Embedding_outdim = 128
output_dim=1
ADD_ON_LAYERS = True
from keras.layers import Dense,LSTM,Activation,Dropout,BatchNormalization,Input,Embedding,Reshape,Concatenate, GRU
from keras.models import Sequential,Model

In [55]:
X_train2= np.asarray(X_train2).astype(np.float32)
X_test2= np.asarray(X_test2).astype(np.float32)

y_train= np.asarray(y_train).astype(np.float32)

X_train= np.asarray(X_train).astype(np.float32)
X_test= np.asarray(X_test).astype(np.float32)

input1 = Input(shape=(X_train2.shape[1],), dtype='float32')
input12 = Embedding(top_words, embedding_vecor_length, input_length=max_review_length)(input1)
input13 = Dropout(0.2)(input12)
input14 = LSTM(100)(input13)
input15 = Dropout(0.2)(input14)
input16 = Dense(64, activation='relu')(input15)
text_vec = Dense(128, activation='sigmoid')(input16)

input2 = Input(shape=(X_train.shape[1],), dtype='float32')
input21 = Dense(128, activation='relu', kernel_initializer='he_normal')(input2)
input22 = Dense(64, activation='relu')(input21)
Poi = Dense(128, activation='sigmoid')(input22)

level_3 = Concatenate()([text_vec,Poi])
print(text_vec.shape)
print(Poi.shape)
print(level_3.shape)

(None, 128)
(None, 128)
(None, 256)


In [56]:
model_in = Dense(DENSE_CONCAT,
    kernel_regularizer=regularizers.l2(weight_decay),
    activation='relu')(level_3)

model_in = Dense(units=int(DENSE_CONCAT/2),
    kernel_regularizer=regularizers.l2(weight_decay),
    activation=None)(model_in)
if ADD_ON_LAYERS:
    model_in = BatchNormalization()(model_in)

model_in = Activation('relu')(model_in)
model_in = Dropout(dropout)(model_in)

model_in = Dense(units=int(DENSE_CONCAT/8),
    kernel_regularizer=regularizers.l2(weight_decay),
    activation=None)(model_in)
if ADD_ON_LAYERS:
    model_in = BatchNormalization()(model_in)

model_in = Activation('relu')(model_in)

main_output = Dense(output_dim, activation='sigmoid')(model_in)

model = Model(inputs=[input1,input2], outputs=main_output)
print(model.summary())

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 50)]         0                                            
__________________________________________________________________________________________________
embedding (Embedding)           (None, 50, 32)       16000       input_1[0][0]                    
__________________________________________________________________________________________________
dropout (Dropout)               (None, 50, 32)       0           embedding[0][0]                  
__________________________________________________________________________________________________
lstm (LSTM)                     (None, 100)          53200       dropout[0][0]                    
______________________________________________________________________________________________

In [57]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [58]:
y_test.shape

(13527, 1)

In [59]:
history = model.fit([X_train2, X_train], y_train, batch_size=32, epochs=30, verbose=1)

Epoch 1/30
859/859 [==============================] - 27s 31ms/step - loss: 0.3575 - accuracy: 0.8407
Epoch 2/30
859/859 [==============================] - 34s 40ms/step - loss: 0.3026 - accuracy: 0.8626
Epoch 3/30
859/859 [==============================] - 35s 41ms/step - loss: 0.2927 - accuracy: 0.8660
Epoch 4/30
859/859 [==============================] - 32s 38ms/step - loss: 0.2872 - accuracy: 0.8684
Epoch 5/30
859/859 [==============================] - 32s 38ms/step - loss: 0.2818 - accuracy: 0.8730
Epoch 6/30
859/859 [==============================] - 32s 37ms/step - loss: 0.2767 - accuracy: 0.8719
Epoch 7/30
859/859 [==============================] - 32s 38ms/step - loss: 0.2743 - accuracy: 0.8735
Epoch 8/30
859/859 [==============================] - 374s 435ms/step - loss: 0.2713 - accuracy: 0.8745
Epoch 9/30
859/859 [==============================] - 26s 30ms/step - loss: 0.2689 - accuracy: 0.8767
Epoch 10/30
859/859 [==============================] - 28s 33ms/step - loss: 0.2

In [60]:
y_true, y_pred =  y_test, model.predict([X_test2, X_test],verbose=verbose)

423/423 - 4s


In [73]:
y_pred

array([[0.9962867 ],
       [0.2581237 ],
       [0.9989011 ],
       ...,
       [0.98361593],
       [0.98144114],
       [0.9920283 ]], dtype=float32)

In [82]:
y_true

array([[1],
       [0],
       [1],
       ...,
       [1],
       [1],
       [1]], dtype=object)

In [75]:
len(y_pred)

13527

In [87]:
y_true=y_true.astype(np.float32)

In [88]:
y_true

array([[1.],
       [0.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], dtype=float32)

In [80]:

for i in range(0,len(y_pred)):
    if y_pred[i]>=0.50:
        y_pred[i]=1
    else:
        y_pred[i]=0

In [89]:
y_pred

array([[1.],
       [0.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], dtype=float32)

In [90]:
from sklearn.metrics import classification_report, confusion_matrix

In [91]:
confusion_matrix(y_true, y_pred)

array([[4269,  689],
       [1025, 7544]])

In [93]:
print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

         0.0       0.81      0.86      0.83      4958
         1.0       0.92      0.88      0.90      8569

    accuracy                           0.87     13527
   macro avg       0.86      0.87      0.87     13527
weighted avg       0.88      0.87      0.87     13527

